// This file is auto-generated by scripts/generateCommunityStats.js
// Do not edit manually. Last generated: 2026-01-18T18:41:33.378Z

export const communityStats = {
    stars: 147,
    forks: 35,
    contributors: 14,
    discordMembers: 1540, // Hardcoded for now, or fetch from Discord widget API if available
    downloads: 5200 // Could be fetched from release assets download_count sum
};
