// This file is auto-generated by scripts/generateContributors.js
// Do not edit manually. Last generated: 2026-01-18T19:01:26.396Z

export interface Contributor {
    login: string;
    avatar_url: string;
    html_url: string;
    contributions: number;
    type: string;
}

export const contributors: Contributor[] = [
    {
        "login": "sharafdin",
        "avatar_url": "https://avatars.githubusercontent.com/u/83120892?v=4",
        "html_url": "https://github.com/sharafdin",
        "contributions": 300,
        "type": "User"
    },
    {
        "login": "shiinedev",
        "avatar_url": "https://avatars.githubusercontent.com/u/171542930?v=4",
        "html_url": "https://github.com/shiinedev",
        "contributions": 17,
        "type": "User"
    },
    {
        "login": "juweyriyo",
        "avatar_url": "https://avatars.githubusercontent.com/u/125019462?v=4",
        "html_url": "https://github.com/juweyriyo",
        "contributions": 15,
        "type": "User"
    },
    {
        "login": "Nasrah-muse",
        "avatar_url": "https://avatars.githubusercontent.com/u/172561895?v=4",
        "html_url": "https://github.com/Nasrah-muse",
        "contributions": 9,
        "type": "User"
    },
    {
        "login": "Adam-Elmi",
        "avatar_url": "https://avatars.githubusercontent.com/u/121925340?v=4",
        "html_url": "https://github.com/Adam-Elmi",
        "contributions": 9,
        "type": "User"
    },
    {
        "login": "Abdiladiif-Abdisamed",
        "avatar_url": "https://avatars.githubusercontent.com/u/181145677?v=4",
        "html_url": "https://github.com/Abdiladiif-Abdisamed",
        "contributions": 8,
        "type": "User"
    },
    {
        "login": "star-Elmi",
        "avatar_url": "https://avatars.githubusercontent.com/u/151863360?v=4",
        "html_url": "https://github.com/star-Elmi",
        "contributions": 7,
        "type": "User"
    },
    {
        "login": "omartood",
        "avatar_url": "https://avatars.githubusercontent.com/u/129175570?v=4",
        "html_url": "https://github.com/omartood",
        "contributions": 7,
        "type": "User"
    },
    {
        "login": "AishaKeyf",
        "avatar_url": "https://avatars.githubusercontent.com/u/147481023?v=4",
        "html_url": "https://github.com/AishaKeyf",
        "contributions": 5,
        "type": "User"
    },
    {
        "login": "mohamedsahal",
        "avatar_url": "https://avatars.githubusercontent.com/u/89407515?v=4",
        "html_url": "https://github.com/mohamedsahal",
        "contributions": 2,
        "type": "User"
    },
    {
        "login": "iftiiin",
        "avatar_url": "https://avatars.githubusercontent.com/u/105747964?v=4",
        "html_url": "https://github.com/iftiiin",
        "contributions": 2,
        "type": "User"
    },
    {
        "login": "Alimoha-1",
        "avatar_url": "https://avatars.githubusercontent.com/u/95440629?v=4",
        "html_url": "https://github.com/Alimoha-1",
        "contributions": 1,
        "type": "User"
    },
    {
        "login": "moelkenzi",
        "avatar_url": "https://avatars.githubusercontent.com/u/149531243?v=4",
        "html_url": "https://github.com/moelkenzi",
        "contributions": 1,
        "type": "User"
    },
    {
        "login": "DevMuna",
        "avatar_url": "https://avatars.githubusercontent.com/u/187665943?v=4",
        "html_url": "https://github.com/DevMuna",
        "contributions": 1,
        "type": "User"
    }
];
