import React from 'react';
import { Icon } from '@iconify/react';

// This file is auto-generated by scripts/generateDownloads.js
// Do not edit manually. Last generated: 2026-01-18T18:23:29.937Z

export const platforms = [
    {
        id: 'windows',
        name: 'Windows',
        icon: <Icon icon="fa6-brands:windows" className="w-12 h-12 text-blue-500" />,
        version: 'v2.0.0',
        type: 'Installer',
        size: '10.7 MB',
        requirements: [
          {
                    'icon': 'lucide:cpu',
                    'text': 'Windows 10/11 (64-bit)'
          },
          {
                    'icon': 'lucide:hard-drive',
                    'text': '500MB Disk Space'
          }
],
        instructions: [
          'Download the installer.',
          'Run the .exe or .msi file.',
          'Follow the setup wizard.'
],
        gradient: 'from-blue-500/20 to-cyan-500/20',
        border: 'group-hover:border-blue-500/50',
        downloadUrl: 'https://github.com/soplang/soplang/releases/download/v2.0.0/soplang-setup.exe',
        files: [
          {
                    'name': 'soplang-setup.exe',
                    'url': 'https://github.com/soplang/soplang/releases/download/v2.0.0/soplang-setup.exe',
                    'size': '10.7 MB',
                    'extension': '.exe'
          }
]
    },
    {
        id: 'linux',
        name: 'Linux',
        icon: <Icon icon="devicon:linux" className="w-12 h-12" />,
        version: 'v2.0.0',
        type: 'Archive/Package',
        size: 'Source',
        requirements: [
          {
                    'icon': 'lucide:cpu',
                    'text': 'Linux (x86_64)'
          },
          {
                    'icon': 'lucide:terminal',
                    'text': 'GLIBC 2.27+'
          }
],
        instructions: [
          'Download the package.',
          'Extract tarball or install .deb/.rpm.',
          'Add to PATH if needed.'
],
        gradient: 'from-green-500/20 to-emerald-500/20',
        border: 'group-hover:border-green-500/50',
        downloadUrl: 'https://api.github.com/repos/soplang/soplang/tarball/v2.0.0',
        files: [
          {
                    'name': 'source-v2.0.0.tar.gz',
                    'url': 'https://api.github.com/repos/soplang/soplang/tarball/v2.0.0',
                    'size': 'Source',
                    'extension': '.tar.gz'
          }
]
    }
];
