const fs = require('fs');
const path = require('path');
const https = require('https');

const OUTPUT_FILE = path.join(__dirname, '../src/constants/communityStats.tsx');
const REPO = 'soplang/soplang';
const API_BASE = 'https://api.github.com/repos';

function fetchJson(url) {
    return new Promise((resolve, reject) => {
        const options = {
            headers: {
                'User-Agent': 'Soplang-Community-Stats-Generator'
            }
        };

        https.get(url, options, (res) => {
            let data = '';
            res.on('data', chunk => data += chunk);
            res.on('end', () => {
                if (res.statusCode >= 200 && res.statusCode < 300) {
                    try {
                        resolve(JSON.parse(data));
                    } catch (e) {
                        reject(new Error('Failed to parse JSON'));
                    }
                } else {
                    reject(new Error(`GitHub API Error: ${res.statusCode} ${res.statusMessage}`));
                }
            });
        }).on('error', err => reject(err));
    });
}

function fetchContributorCount() {
    // Determine contributor count by fetching 1 contributor per page and getting the 'last' page from Link header
    return new Promise((resolve, reject) => {
        const url = `${API_BASE}/${REPO}/contributors?per_page=1&anon=true`;
        const options = {
            headers: {
                'User-Agent': 'Soplang-Community-Stats-Generator'
            }
        };

        https.get(url, options, (res) => {
            if (res.statusCode >= 200 && res.statusCode < 300) {
                const linkHeader = res.headers.link;
                if (linkHeader) {
                    // Parse link header: <...page=2>; rel="next", <...page=12>; rel="last"
                    const match = linkHeader.match(/page=(\d+)>; rel="last"/);
                    if (match) {
                        resolve(parseInt(match[1], 10));
                        return;
                    }
                }
                // Fallback: If no link header (likely only 1 page of contributors), parse body length
                let data = '';
                res.on('data', chunk => data += chunk);
                res.on('end', () => {
                    try {
                        const json = JSON.parse(data);
                        resolve(json.length);
                    } catch (e) {
                        resolve(0);
                    }
                });
            } else {
                reject(new Error(`GitHub API Error: ${res.statusCode} ${res.statusMessage}`));
            }
        }).on('error', err => reject(err));
    });
}

async function generateStats() {
    try {
        console.log('Fetching community stats from GitHub...');

        // Parallel fetch
        const [repoData, contributorCount] = await Promise.all([
            fetchJson(`${API_BASE}/${REPO}`),
            fetchContributorCount()
        ]);

        const stats = {
            stars: repoData.stargazers_count,
            forks: repoData.forks_count,
            contributors: contributorCount
        };

        console.log(`Fetched: ${stats.stars} Stars, ${stats.forks} Forks, ${stats.contributors} Contributors`);

        const fileContent = `// This file is auto-generated by scripts/generateCommunityStats.js
// Do not edit manually. Last generated: ${new Date().toISOString()}

export const communityStats = {
    stars: ${stats.stars},
    forks: ${stats.forks},
    contributors: ${stats.contributors},
    discordMembers: 1540, // Hardcoded for now, or fetch from Discord widget API if available
    downloads: 5200 // Could be fetched from release assets download_count sum
};
`;

        // Ensure directory exists
        const dir = path.dirname(OUTPUT_FILE);
        if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir, { recursive: true });
        }

        fs.writeFileSync(OUTPUT_FILE, fileContent);
        console.log(`Successfully generated ${OUTPUT_FILE}`);

    } catch (error) {
        console.error('Error generating community stats:', error);
        // Fallback to safe defaults if API fails during build
        console.log('Generating fallback data due to error...');

        const fallbackContent = `// This file is auto-generated by scripts/generateCommunityStats.js
// FALLBACK DATA GENERATED DUE TO ERROR: ${error.message}
// Last generated: ${new Date().toISOString()}

export const communityStats = {
    stars: 100,
    forks: 20,
    contributors: 5,
    discordMembers: 1500,
    downloads: 5000
};
`;
        fs.writeFileSync(OUTPUT_FILE, fallbackContent);
        // Do not exit with error code to prevent build failure
    }
}

generateStats();
