const fs = require('fs');
const path = require('path');
const https = require('https');

const OUTPUT_FILE = path.join(__dirname, '../src/constants/contributorsData.tsx');
const REPO = 'soplang/soplang';
const API_URL = `https://api.github.com/repos/${REPO}/contributors`;

function fetchContributors() {
    return new Promise((resolve, reject) => {
        const options = {
            headers: {
                'User-Agent': 'Soplang-Contributor-Generator'
            }
        };

        https.get(API_URL, options, (res) => {
            let data = '';
            res.on('data', chunk => data += chunk);
            res.on('end', () => {
                if (res.statusCode >= 200 && res.statusCode < 300) {
                    try {
                        resolve(JSON.parse(data));
                    } catch (e) {
                        reject(new Error('Failed to parse JSON'));
                    }
                } else {
                    reject(new Error(`GitHub API Error: ${res.statusCode} ${res.statusMessage}`));
                }
            });
        }).on('error', err => reject(err));
    });
}

async function generateData() {
    try {
        console.log('Fetching contributors from GitHub...');
        const contributors = await fetchContributors();

        const formattedContributors = contributors.map(c => ({
            login: c.login,
            avatar_url: c.avatar_url,
            html_url: c.html_url,
            contributions: c.contributions,
            type: c.type
        })).filter(c => c.type === 'User'); // Filter out bots if needed

        console.log(`Found ${formattedContributors.length} contributors.`);

        const fileContent = `// This file is auto-generated by scripts/generateContributors.js
// Do not edit manually. Last generated: ${new Date().toISOString()}

export interface Contributor {
    login: string;
    avatar_url: string;
    html_url: string;
    contributions: number;
    type: string;
}

export const contributors: Contributor[] = ${JSON.stringify(formattedContributors, null, 4)};
`;

        // Ensure directory exists
        const dir = path.dirname(OUTPUT_FILE);
        if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir, { recursive: true });
        }

        fs.writeFileSync(OUTPUT_FILE, fileContent);
        console.log(`Successfully generated ${OUTPUT_FILE}`);

    } catch (error) {
        console.error('Error generating contributors:', error);

        // Fallback data if API fails (e.g. rate limit)
        console.log('Generating fallback data due to error...');
        const fallbackData = [
            { login: 'Sharafdin', avatar_url: 'https://github.com/Sharafdin.png', html_url: 'https://github.com/Sharafdin', contributions: 100, type: 'User' },
            { login: 'SoplangBot', avatar_url: 'https://github.com/soplang.png', html_url: 'https://github.com/soplang', contributions: 50, type: 'User' }
        ];
        const fileContent = `// This file is auto-generated by scripts/generateContributors.js
// FALLBACK DATA GENERATED DUE TO ERROR: ${error.message}
// Last generated: ${new Date().toISOString()}

export interface Contributor {
    login: string;
    avatar_url: string;
    html_url: string;
    contributions: number;
    type: string;
}

export const contributors: Contributor[] = ${JSON.stringify(fallbackData, null, 4)};
`;
        fs.writeFileSync(OUTPUT_FILE, fileContent);
    }
}

generateData();
